version: '3'
services:
  saml2:
    build: .
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: https://localhost:8000/saml/metadata
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: https://localhost:8000/saml/acs
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: https://localhost:8000/saml/logout
      SIMPLESAMLPHP_ADMIN_PASSWORD: test
      SIMPLESAMLPHP_SECRET_SALT: salt
    ports:
    - "8888:8888"
    - "8443:8443"
    #volumes:
    #- /users.php:/var/www/simplesamlphp/config/simplesamlphp/authsources.php
